### ISSUE TITLE
Let user choose what file/files are source of identity hash.

### ISSUE THREAD

**Issue by Svaca** [Container-Driven-Development/soos#11]
Hi Mario, 
my use case is that my project is uses 2 files:
- package.json
- composer.json (php package manager)

Therefore we need to make possible to set up a list of files to be hashed.
Idealy with relative path.

Thanks
Svaca

**Comment by devopsmariocom** [comment]
Thank you @Svaca for your feature request, please let me know how is soos working for you 😉
